stages:
  - unittest

unittest:
  stage: unittest
  image: composer:latest
  cache:
    key: $CI_PROJECT_NAME
    policy: pull
    paths:
      - vendor
      - composer.lock
  script:
    - apk add --no-cache $PHPIZE_DEPS
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - composer install
    - ./vendor/bin/phpunit --coverage-text tests -v --testdox