<?php

namespace OneId\Api\NonceManager;

use PHPUnit\Framework\TestCase;

class RandomNonceManagerTest extends TestCase
{
    /**
     * @var RandomNonceManager
     */
    protected $nonceManager;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->nonceManager = new RandomNonceManager();
    }


    public function testGenerateNonce()
    {
        $generatedNonce = [];
        for ($i=0;$i<100;$i++) {
            $nonce = $this->nonceManager->generateNonce();
            $this->assertNotContains($nonce, $generatedNonce);
            array_push($generatedNonce, $nonce);
        }
    }
}